name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
     - completed

jobs:

    build:
        runs-on: self-hosted

        steps:
        - name: Log in to Docker Hub
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

        - name: pull docker image
          run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/gym-project:latest
                 
        - name: Stop and remove existing container
          run: docker rm -f gym-project || true

        # - name: Run docker container 
        #   run: sudo docker run -d -p 8080:8080 --name gym-project ${{ secrets.DOCKER_USERNAME }}/gym-project:latest
        - name: Run Docker container
          run: |
            sudo docker run -d -p 8080:3000 --name gym-project \
            -e REACT_APP_RAPID_API_KEY="${{ secrets.REACT_APP_RAPID_API_KEY }}" \
            ${{ secrets.DOCKER_USERNAME }}/gym-project:latest

